### ISSUE TITLE
Null error catched in this.recaptchaService.execute

### ISSUE THREAD

**Issue by pdoorr** [LCGroupIT/angular-recaptcha3#2]
Hi,
I would like to catch errors executing the recaptcha service then I've added the below catch block:
this.recaptchaService.execute({ action: 'login' }).then(token
....
}).catch((error) => {
      console.log(error);
    });

I've tried it removing the domain from the captcha console but the printed error is a null. How can I get the raised exception?

Thanks,
fabio

**Comment by Romanchuk** [comment]
Hello, execute in service just passing through original recaptcha execute:

```
public execute(options: any = undefined): Promise<string> {
        const captcha = (<any>window).grecaptcha;
        const captchaElement = document.querySelector('.g-recaptcha.invisible');

        return captcha.execute(captchaElement.id, options);
    }
```
So it is the question to google
By the way, there is nothing about catching exception in docs https://developers.google.com/recaptcha/docs/v3

**Comment by pdoorr** [comment]
Thanks Sergey.

Il giorno ven 28 ago 2020 alle ore 08:50 Sergey Romanchuk <
notifications@github.com> ha scritto:
