### ISSUE TITLE
ERROR for site owner: Invalid key type

### ISSUE THREAD

**Issue by TheDevelolper** [LCGroupIT/angular-recaptcha3#6]
I'm specifying the sitekey in th script tag: 

```html 
<script src="https://www.google.com/recaptcha/api.js?render=[my key here]"></script>
```
in the template:
``` html
  <div *ngIf="loginForm.dirty && showRecapcha" class="flex align-items-center justify-content-center mb-5">
    <recaptcha
    [size]="'normal'"
    [hide]="false"
    [sitekey]="'[my key here]'"
    (captchaResponse)="onCaptchaResponse($event)">
    </recaptcha>
```
in the module: 

```typescript

ReCaptchaModule.forRoot({
      invisible: {
        sitekey: '[my key here]',
    },
      normal: {
        sitekey: '[my key here]',
    },
    language: 'en'
    })

```

![image](https://user-images.githubusercontent.com/4026553/134787229-31379196-c5cd-4c90-bfa7-d29763a6a106.png)

My sitekey has been replaced with [my key here] above to protect it. It matches what's in the cloud platform console. (which is definitely using a V3 recaptcha). 

yet I am still getting: 

![image](https://user-images.githubusercontent.com/4026553/134787159-83d78584-9072-4463-ac67-7e55ecce4215.png)

I can't think of anything I've missed here?

**Comment by vreactor** [comment]
@FacePalmDev You dont need to add a script tag to the site, because the library does it for you.
